core: implement file tree for hashmap
lockbook/lockbook pull request #1084
Opened 2022-05-04 02:14 UTC by vvmirkovic

- [ ] Implement FileMetaExt on HashMap<Uuid, FileMetadata>
- [ ] Make benchmarks
- [ ] Replace other code to use hashmaps instead of vets, in places such as Tx, so that they use O(1) hashmap methods instead of >O(n) vec methods

This is one step of this journey:  #1059

2022-06-09 21:05 UTC, steverusso requested changes

2022-06-10 03:29 UTC, steverusso requested changes
Also: there's a few places where `insert(id, fm)` is used instead of the `push(fm)` fn. Should we prioritize `push` for readability?

2022-06-10 03:29 UTC, steverusso commented on core/libs/models/src/tree.rs
> +            .filter(|(_, f)| f.file_type() == FileType::Document)
```suggestion
            .filter(|(_, f)| f.file_type() == Document)
```
`FileType`'s variants got imported for this file with this PR. So if we are going to keep the variants, then let's drop the enum prefix just right here for now.

2022-06-10 03:29 UTC, steverusso commented on core/libs/test_utils/src/lib.rs
> +                .map(|s| (s.0, s.1 .0))
Can what's going on here be a little clearer?

2022-06-10 19:28 UTC, Parth approved these changes

2022-06-10 19:49 UTC, steverusso approved these changes

2022-06-10 19:58 UTC, merged