admin: list premium users
lockbook/lockbook pull request #1368
Opened 2022-09-09 16:10 UTC by SmailBarkouch

fixes #1367

2022-09-13 14:30 UTC, Parth requested changes

2022-09-13 14:30 UTC, Parth commented on core/libs/shared/src/api.rs
> +}
very un-worthwhile imo, just return the `PaymentPlatform`

2022-09-14 23:18 UTC, Parth requested changes
checkout #1372, once it's merged, rebase and migrate these changes into that

2022-09-17 13:05 UTC, steverusso requested changes

2022-09-17 15:43 UTC, Parth requested changes
>  also I think you're going to want to setup structure that allows us to list all users, and have arbitrary filters

2022-09-17 15:52 UTC, Parth commented
I'm still thinking about this, but maybe this is what we need:

A way to list users, and a way to get all the info we have on a particular user.

Listing users maybe we want to filter, this is the first filter we've come up with (premium) but likely we'll add more filters in the future, like root created after a specified date or whatever.

When we get the info for a user we should be able to specify a username or a public key, and it should print out all the billing info (and we can add other data points it prints out later) Data like which files they own, who they share files with, etc.

2022-09-17 15:53 UTC, Parth commented
In the future we can add filters as we need and data on a user's "profile" as we need. Maybe we make a lil egui app for this not sure.

2022-09-20 18:20 UTC, Parth approved these changes

2022-09-20 19:23 UTC, steverusso commented on clients/admin/src/main.rs
> +        return Ok(());
nit: this feels like an error to run account info without providing a username or public key

2022-09-20 19:25 UTC, steverusso commented on core/src/lib.rs
> +pub use libsecp256k1::PublicKey;
Please toss these with the other third party pub uses (uuid above) and not with the crates.

2022-09-20 19:26 UTC, steverusso commented on core/src/lib.rs
>  pub use lockbook_shared::api::{PaymentMethod, PaymentPlatform};
Might as well combine these now

2022-09-22 20:29 UTC, merged