admin, server: improved `get_account_info`
lockbook/lockbook pull request #1423
Opened 2022-10-03 16:25 UTC by SmailBarkouch

2022-10-04 02:32 UTC, tvanderstad commented on clients/admin/src/account.rs
> +    println!("usage: {}B", account_info.usage);
Thoughts about using our human readable bytes function here? The number would be less precise but maybe we'd want "10.1MB" instead of "1014349B"

2022-10-04 15:11 UTC, Parth commented on clients/admin/src/account.rs
> +    )
+ I think we just want to `{:#?}` this
+ I don't think we want to say how long ago they were active, I think we want to print the date / time they were last active. I think if this object contained an `Instant` or something the debug print would handle that too.
+ if you need to give anything special attention, consider impl'ing `Debug` the way we do for `Trial`.

2022-10-08 18:16 UTC, Parth requested changes

2022-10-08 18:16 UTC, Parth commented on server/server/src/account_service.rs
> +                last_active = metadata.version
This won't capture modifications to shared files, I think we actually can't capture this field without storing data on the server, so I'm down to remove `last_active` from this entirely for now.

2022-10-16 17:23 UTC, Parth approved these changes

2022-10-16 17:58 UTC, merged