core, server: set size limits on userfields
lockbook/lockbook pull request #1515
Opened 2023-01-13 19:27 UTC by ad-tra

context: core, server
fixes: #1228

2023-01-13 19:31 UTC, ad-tra commented on libs/core/libs/shared/src/api.rs
> +    FileNameTooLong,
> @parth: prob doesn't need to be here
the file name length should be checked both in upsert and when the user renames. So it should be included.

2023-01-13 19:31 UTC, ad-tra commented on libs/core/src/service/account_service.rs
> +        if username.len() > 254 {
> @Parth this can prob be a smaller value lol, I think like 20

2023-01-18 22:08 UTC, Parth requested changes
Your approach for usernames is fine. 

Your approach for filenames is not quite what we want:

You don't want to hunt down all the places that names could change. 

Checkout `validate.rs`, specifically the `validate()` function. You can add a size check (on the encrypted copy). And it will apply everywhere (renames, paths, creates etc).

2023-01-22 21:04 UTC, Parth requested changes
This looks better, but a few more things required:
+ [x] `get_encryption_overhead` shouldn't be called for usernames, they're always cleartext.
+ [x] that function is only ever called with 1 value (right?) you can just have a const for the `MAX_ENCRYPTED_FILENAME_LENGTH` with the math hardcoded
 + [x] you want to go through `lib.rs` and see which endpoints could cause a filename to become too long (create, rename, etc) and you don't want this new error (`FileNameTooLong`) to be mapped to `Unexpected`. You want it to be handled by our various clients.
 + [ ] when you do this, a handful of clients will break, you want to chase down those compiler errors and CI failures and fix them.
 + [ ] Currently if you use CLI to create a file with a name too long you'll just get an `Unexpected`, the target state would provide a better error message, and our tooling should help you do that. @SmailBarkouch can do iOS and android.
+ [ ] is a UUID 50 characters long? I thought it was shorter than that by a good margin.

2023-03-01 02:02 UTC, Parth requested changes
get this rebased and we'll get the errors piped through this week

2023-03-01 02:02 UTC, Parth commented on libs/core/libs/shared/src/validate.rs
> +            if file.secret_name().encrypted_value.value.len() > MAX_ENCRYPTED_FILENAME_LENGTH {
deserves it's own fn, idk if it makes sense to tack this check onto this fn

2023-03-01 02:02 UTC, Parth commented on libs/core/tests/file_ops.rs
> +    let result = core.create_at_path(&"x".repeat(MAX_FILENAME_LENGTH + 1));
is this a copy paste error?

2023-03-23 15:21 UTC, ad-tra commented
Make sure not to return unexpected

2023-03-26 20:25 UTC, Parth commented
Before we merge this, we need to run the new validations with the current server data to make sure there aren't any files currently that are too long

2023-03-26 23:55 UTC, Parth approved these changes

2023-03-27 01:35 UTC, steverusso requested changes

2023-03-27 01:35 UTC, steverusso commented on libs/core/libs/shared/src/validate.rs
> -
Leave this in, and then...

2023-03-27 01:35 UTC, steverusso commented on libs/core/libs/shared/src/validate.rs
> +    }
... add one to give functions some breathing room.

2023-03-27 01:35 UTC, steverusso commented on libs/core/src/lib.rs
@Parth should `create_at_path` also have `FileNameTooLong` as an expected error?

2023-03-27 01:35 UTC, steverusso commented on server/server/src/utils.rs
> +};
```suggestion
use lockbook_shared::account::MAX_USERNAME_LENGTH;
use lockbook_shared::api::{GetBuildInfoError, GetBuildInfoResponse};
```

2023-03-27 01:35 UTC, steverusso commented on server/server/src/file_service.rs
> +
```suggestion
```
Try to remove all standalone inconsequential changes like this, esp before final review.

2023-03-27 18:01 UTC, steverusso commented on libs/core/src/lib.rs
@ad-tra @Parth will `create_at_path` ever return a `FileNameTooLong`? Don't we have to check the path components?

2023-03-27 21:51 UTC, Parth requested changes

2023-03-27 21:51 UTC, Parth commented on libs/core/src/lib.rs
@ad-tra `create_link_at_path` too. Can you throw some sanity-check-tests in there too?

2023-03-28 12:33 UTC, steverusso approved these changes

2023-03-28 13:47 UTC, merged