apple: suggested documents
lockbook/lockbook pull request #1748
Opened 2023-04-29 15:20 UTC by SmailBarkouch

iOS design:
<details>

![Simulator Screen Shot - iPhone 14 Pro - 2023-04-29 at 10 53 32](https://user-images.githubusercontent.com/20663038/235310294-d34f0b48-ba91-4d4d-a071-f4ecfc016a6d.png)
</details>

iPad design:
<details>

![Simulator Screen Shot - iPad (10th generation) - 2023-04-29 at 10 43 40](https://user-images.githubusercontent.com/20663038/235310310-5be0ad58-e1f3-4990-b3e8-3abe5d2d53dc.png)
</details>

macOS design:
<details>

<img width="1146" alt="Screenshot 2023-04-29 at 11 17 44 AM" src="https://user-images.githubusercontent.com/20663038/235310300-233eb6f3-81ba-4692-b9f8-d799842eba0a.png">
</details>

2023-04-29 19:11 UTC, Parth requested changes
+ thoughts on making macOS look closer to iOS? I would even be down for iPad to look closer to iPhone (more compact)
+ did you checkout what order sync is called on initial load compared to things like suggested docs / list files?

2023-04-29 19:11 UTC, Parth commented on clients/apple/Shared/Views/DocumentView.swift
> +            DI.files.refreshSuggestedDocs()
have you confirmed this is ever called?

2023-04-29 19:11 UTC, Parth commented on clients/apple/iOS/SuggestedDocs.swift
is it possible that this UI element will load and then cause someone to click on the wrong file?

2023-04-29 21:25 UTC, SmailBarkouch commented on clients/apple/Shared/Views/DocumentView.swift
> +            DI.files.refreshSuggestedDocs()
I have confirmed.

2023-04-29 21:26 UTC, SmailBarkouch commented on clients/apple/iOS/SuggestedDocs.swift
On initial load it will have a temporary view with the same size as the real one, so it will not. Only case it may is if there are no suggested docs to begin with, so the loaded view is nothing.

2023-04-30 21:17 UTC, Parth approved these changes
looks sick, can't wait to release this

2023-05-01 12:09 UTC, merged