cli: add cli completions
lockbook/lockbook pull request #1764
Opened 2023-05-21 06:04 UTC by ad-tra

fixes: #878

2023-06-14 20:20 UTC, ad-tra commented
#### BASH 

Append to  `~/.bashrc`:

`source < {path_to_lb_completion_script}`


#### ZSH 

Append the following to `~/.zshrc`:

    autoload -U +X bashcompinit && bashcompinit
    source < {path_to_lb_completion_script}

2023-06-20 17:21 UTC, Parth requested changes

2023-06-28 11:38 UTC, ad-tra commented on clients/cli/src/completions.rs
> +pub fn complete(core: &Core, input: String, current: i32) -> Result<(), CliError> {
i converted `CliError` into an enum that houses two error variants, one that prints to console and one that doesn't (it prints to console on non release builds for ease of development)

2023-06-28 11:58 UTC, ad-tra commented on clients/cli/src/completions.rs
> +        Shell::Bash | Shell::Zsh => print!("{}", BASH_COMPLETIONS),
to install bash completions on zsh, you need to [init them](https://stackoverflow.com/questions/67136714/how-to-properly-call-compinit-and-bashcompinit-in-zsh) with `autoload -U +X bashcompinit && bashcompinit` did you do that?

2023-06-28 12:23 UTC, ad-tra commented on clients/cli/src/completions.rs
> +        .nth(current as usize - 2)
the input array: `[lockbook, subcommand (ex: edit), arg 1, arg2, .. , arg_n ]`
the arguments array: `[arg 1, arg2, .. , arg_n ]`

we want the current arg from the args array, based on the cursor in the input array. hence the offset of 2

the case where there will be index out of bounds is if you don't provide a subcommand. but this arg finding segment wouldn't execute as the no subcommand error case is caught earlier by  

```rust 

    let matched_subcommand = matches
        .subcommand()
        .ok_or(CliError::SilentError("no subcommand provided in the input".to_string()))?;
```

2023-06-28 15:56 UTC, Parth approved these changes
LGTM, a lil unsure about how we are presently handling zsh bash compatibility, I think we ought to make it more clear that we're falling back to a compat mode so someone knows to config it

2023-06-28 15:56 UTC, Parth commented on clients/cli/src/error.rs
> +    ConsoleError(String),
```suggestion
    Console(String),
    Silent(String),
```

2023-06-28 20:36 UTC, merged