Android launch with core
lockbook/lockbook pull request #329
Opened 2020-10-06 16:28 UTC by SmailBarkouch

Now you are determined to be logged in with the core. You're state can correctly be identified. (close #276 )
Better handled nullables (close #210 )

**Note I have not tested migration since I don't know how to do that. If you know how to let me know.**

2020-10-09 18:07 UTC, Parth requested changes

2020-10-20 20:42 UTC, SmailBarkouch commented on clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/FileModel.kt
> +                        UNEXPECTED_CLIENT_ERROR
Shouldn't be using that constant.

2020-10-20 20:42 UTC, SmailBarkouch commented on clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/FileModel.kt
> +                        UNEXPECTED_CLIENT_ERROR
Get rid of internet checks, just let them know they have no internet when they try to do something that does.

2020-10-20 20:42 UTC, SmailBarkouch commented on clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/FileModel.kt
> +                        UNEXPECTED_ERROR
Shouldn't be posting the constant.

2020-10-20 20:42 UTC, SmailBarkouch commented on clients/android/app/src/main/java/app/lockbook/utils/Converters.kt
> +                        else -> {}
This should not be empty

2020-10-20 20:42 UTC, SmailBarkouch commented on clients/android/app/src/main/java/app/lockbook/utils/Converters.kt
> +                            else -> CreateAccountError.Unexpected("Can't recognize UiError content.")
Make error more specific enough to allow a person to find out where exactly it happened.

2020-10-20 20:42 UTC, merged