windows: utf8 documents, prompt for update, refactor
lockbook/lockbook pull request #537
Opened 2021-01-18 19:49 UTC by tvanderstad

2021-01-20 03:04 UTC, Parth commented on clients/windows/lockbook/Settings.xaml.cs
> +        const ulong KILOBYTES = BYTE * 1000;
https://github.com/lockbook/lockbook/pull/502

should probably use this, hot off the press

2021-01-20 03:08 UTC, Parth commented on clients/windows/lockbook/App.xaml.cs
>  using System.Threading.Tasks;
This commit message: `dont exit app when clearing state, auto clear state when needed` doesn't seem to be what actually happens -- we don't actually nuke a user's state on `StateRequiresCleaning` do we? If so we should not.

2021-01-20 03:09 UTC, Parth commented on clients/windows/lockbook/SignUp.xaml
> +                    <TextBox
Not on board with all users seeing this, it should be behind some debug config or something

2021-01-20 03:10 UTC, Parth requested changes
Left some comments in the commits, also this closes several issues, you should add closes statements. I'll throw this on a device and QA it when you're ready

2021-01-24 07:18 UTC, tvanderstad commented
closed in favor of https://github.com/lockbook/lockbook/pull/551 due to a mysterious yet tragic git accident

2021-01-24 07:18 UTC, closed without merging