infra: shorten kotlin interface tests prep and run time
lockbook/lockbook pull request #591
Opened 2021-02-08 23:50 UTC by SmailBarkouch

fixes #553

2021-02-12 23:23 UTC, Parth commented
Try to remove `RUN gradle compileDebugUnitTestSources` and see if it reduces the time, maybe it's not as helpful as I thought it was.

2021-02-12 23:23 UTC, Parth requested changes
Try to remove `RUN gradle compileDebugUnitTestSources` and see if it reduces the time, maybe it's not as helpful as I thought it was.

2021-02-13 16:58 UTC, SmailBarkouch commented
> Try to remove `RUN gradle compileDebugUnitTestSources` and see if it reduces the time, maybe it's not as helpful as I thought it was.

I tried that and it increased all the way up to 3 minutes. I reran it also just to make sure (in case there was some sort of caching I didn't know about).
<details>

![test](https://user-images.githubusercontent.com/20663038/107855817-a1dc1380-6df2-11eb-9ce2-3396f2ece23e.png)
</details>

2021-02-13 17:25 UTC, Parth approved these changes

2021-02-13 17:38 UTC, merged