server: usage caps
lockbook/lockbook pull request #814
Opened 2021-07-11 19:49 UTC by raayan

```zsh
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ lipsate 100000 | ../../target/debug/lockbook edit nice/test.txt --stdin
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook sync                                       
Pushing: test.txt
Sync complete.
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ lipsate 100000 | ../../target/debug/lockbook edit nice/test.txt --stdin
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook get-usage                                  
Uncompressed File Size: 100 KB
Server Utilization: 23.03 KB
Server Data Cap: 100 KB
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook sync                                       
Pushing: test.txt
Sync complete.
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook get-usage
Uncompressed File Size: 100 KB
Server Utilization: 22.46 KB
Server Data Cap: 100 KB
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ lipsate 500000 | ../../target/debug/lockbook edit nice/test.txt --stdin
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook get-usage                                  
Uncompressed File Size: 500 KB
Server Utilization: 22.46 KB
Server Data Cap: 100 KB
raayan@raayan-p15 ~/dev/lockbook/clients/cli [raayan/usage_caps] $ ../../target/debug/lockbook sync
Pushing: test.txt
[2021-07-11 15:45:01] [lockbook_core::service::sync_service    ] [ERROR]: Sync error detected: LocalChange {
    metadata: FileMetadata {
        id: fec0ae6c-eaa9-4783-bf57-ff508fd91750,
        file_type: Document,
        parent: e61cc7ec-0e1c-4eda-acf2-bcba6c371c62,
        name: SecretFileName {
            encrypted_value: AESEncrypted {
                value: [
                    143,
                    197,
                    206,
                    93,
                    144,
                    31,
                    121,
                    247,
                    213,
                    97,
                    87,
                    74,
                    65,
                    30,
                    104,
                    156,
                    30,
                    59,
                    143,
                    223,
                    88,
                    14,
                    242,
                    247,
                    130,
                    77,
                    101,
                    105,
                    254,
                    121,
                    55,
                    78,
                ],
                nonce: [
                    216,
                    77,
                    129,
                    94,
                    20,
                    179,
                    165,
                    93,
                    128,
                    130,
                    138,
                    70,
                ],
                _t: PhantomData,
            },
            hmac: [
                237,
                200,
                103,
                99,
                77,
                186,
                115,
                149,
                74,
                72,
                69,
                190,
                53,
                12,
                209,
                170,
                229,
                169,
                156,
                118,
                110,
                227,
                59,
                230,
                142,
                255,
                15,
                53,
                9,
                104,
                165,
                3,
            ],
        },
        owner: "nice",
        metadata_version: 1626032473171,
        content_version: 1626032473171,
        deleted: false,
        user_access_keys: {},
        folder_access_keys: AESEncrypted {
            value: [
                220,
                46,
                163,
                50,
                146,
                1,
                39,
                127,
                50,
                54,
                128,
                127,
                188,
                9,
                213,
                159,
                109,
                16,
                225,
                221,
                227,
                52,
                12,
                146,
                62,
                96,
                79,
                17,
                235,
                107,
                96,
                109,
                100,
                45,
                30,
                41,
                161,
                61,
                26,
                92,
                249,
                147,
                75,
                147,
                200,
                245,
                145,
                205,
            ],
            nonce: [
                56,
                68,
                255,
                57,
                31,
                44,
                165,
                241,
                18,
                15,
                29,
                116,
            ],
            _t: PhantomData,
        },
    },
} Unexpected(
    "Endpoint(
    DataCapExceeded,
)",
)
```

ft. brutal logs

2021-07-11 20:05 UTC, Parth requested changes
Good first steps, we want this error to make it to `lib.rs` and be an explicit error for `sync`.

2021-07-11 20:09 UTC, raayan commented
@Parth isn't @tvanderstad changing sync significantly atm?

2021-07-11 20:32 UTC, Parth commented
Yeah he is, but this error will exist in his work too. I think there's only a small amount of stuff that will be duplicated. @tvanderstad a lot of errors are treated like: "pull and we'll retry", this is not one of those errors. So for both SyncV2 (what @raayan will slightly modify) and SyncV3 (what @tvanderstad is working on), if we see this error, we want to put the breaks on and propagate this up to the user.

imo this is a small part of this body of work, the more significant part is the UX around approaching the limit, warning users, and then finally indicating to them that it's time to buy more space.

If you wanted to pause this body of work until SyncV3 is merged, you could start working on some of the streams of work required for actually adding a payment method on various platforms (see the doc).

2021-07-12 02:06 UTC, raayan commented on core/src/service/sync_service.rs
> +                Err(CoreError::DataCapExceeded) => return Err(CoreError::DataCapExceeded),
This is notable, we boot out of the sync process here

2021-11-17 21:48 UTC, Parth commented
> @Parth isn't @tvanderstad changing sync significantly atm?
@raayan was right

```
Conflicting files
clients/cli/src/edit.rs
clients/cli/src/main.rs
clients/cli/src/new.rs
clients/cli/src/utils.rs
core/libs/models/src/api.rs
core/src/lib.rs
core/src/service/sync_service.rs
server/server/src/file_index_repo.rs
server/server/src/file_service.rs
```

2021-11-17 21:48 UTC, closed without merging

2021-11-17 21:49 UTC, Parth commented
Will be copying from this PR in a new PR soon to be linked