linux: filetree tweaks and icons
lockbook/lockbook pull request #825
Opened 2021-07-16 16:24 UTC by SmailBarkouch

2021-07-16 22:49 UTC, steverusso commented on clients/linux/src/menubar.rs
> +    fn data() -> Vec<(Self, Option<String>, ItemData)> {
Why not do a static string (`&'static str`) type here instead of a `Option<String>`? Seems a bit cluttered

2021-07-18 14:35 UTC, Parth requested changes
Okay tried it out locally, here are some thoughts:
+ remove icons from things that aren't the file tree

Can we do the following (maybe within it's own PR):
+ allow the filetree to scroll while doing a move?
+ un-expand things if you leave that folder's region?

Also maybe in it's own PR:
+ would a setting to toggle between symbolic icons require a restart? Maybe there's a good way to express which settings require a restart and which don't.

2021-07-22 23:33 UTC, Parth commented on clients/linux/src/filetree.rs
> +            if y > height - 50 || y < 50 {
Add some comments here

2021-07-22 23:45 UTC, Parth approved these changes

2021-07-23 21:55 UTC, merged