public_site: v2
lockbook/lockbook pull request #826
Opened 2021-07-17 01:37 UTC by Parth

2021-07-20 16:39 UTC, plv commented
Could you add screenshots of the site to the PR desc?

2021-07-23 23:07 UTC, steverusso requested changes

2021-07-23 23:07 UTC, steverusso commented on public_site/index.html
> +							so even we can’t see them. Don’t take our word for it: Lockbook is 100% open-source.
```suggestion
							Privacy shouldn’t be a compromise. That’s why we made Lockbook, a secure companion to record, sync, and share your thoughts with apps engineered to
							feel like home on every platform. We collect no personal information and encrypt your notes
							so even we can’t see them. Don’t take our word for it: Lockbook is 100% open-source.
```
It felt a bit redundant / awkward at certain parts. This is just a rough simplification that can probably be refined further.

2021-07-24 11:50 UTC, steverusso reviewed
Looks good to me

2021-07-25 13:51 UTC, merged

2021-07-28 00:48 UTC, plv commented
I have myriad design nits (will list below) but otherwise I think this is a good start. Also, I don't know how much modern web development matters for landing pages but there's some improvements that can be made there, but again I won't touch on that for now.

w/r/t design:
1) For the first screen (black background):
* There's a lot of empty space going on here to the point where the page looks like it hasn't finished loading.  Off the top of my head we can take a look at putting a Lockbook logo in the top left corner and perhaps a header bar with links to the various sections. If we do this, then it would be good to replace the "Lockbook" text in the white box with the subheading ("The best place to store and share thoughts").
* top and bottom padding in the white box is much higher than the left padding. Would increase left padding by a few px so that the `LOCKBOOK` is ever so slightly more indented
* Where is the download links / call to action at?
* Going from black background to a softer dark grey  is more visually appealing 

2) For the red screen:
* The platform icons should be left-aligned. It looks jarring because it's the only center-justified thing onscreen.
* I feel like our screenshots could be better here, but I also think that the apps' designs could be improved. Completely separate conversation.

3) For the blue "honest" screen:
* The shade of blue doesn't look good with the colors we use for the "check" and "x" icons. Would do us good to change the shade. If you ask me personally I think the entire site should go with a different color palette, but again this is a separate conversation.
* Technically we make our money by selling storage, not a note taking app
* Again, centered prices look weird. Left-align them, maybe even add a "Pricing" subheader
* Would also left-align the text in the first column of the table, but I'm less sure about this one so I'd have to see it to make a call

4) The "developer friendly" screen:

* In the future if we have communities on Discord, Stack Overflow, Github issues, etc. it would be good to have buttons and calls to action here
* Going from black background to a softer dark grey  is more visually appealing

2021-07-28 00:49 UTC, plv commented
Oh, I didn't realize you already merged this lol. Keeping my comment as notes for future iterations