linux: links
lockbook/lockbook pull request #834
Opened 2021-08-01 15:52 UTC by SmailBarkouch

In this PR, you can now have links in your lockbook documents. This means you can link to documents and folders on lockbook, as well as arbitrary files or website links. 

To add a link to a lockbook file you simply follow the format of a regular markdown link, and inside the parenthesis you write out the absolute path of the lockbook file, prefixing it with "lb://". You will know the format is valid once the markdown link is bolded red. These are some valid examples:
```
[here](lb://options/info.md)
[there](lb://school/assignment-due-today.md)
```

To link to websites or local files, make sure to include the protocol. Some valid examples:
```
[google](https://google.com)
[lockbook](https://github.com/lockbook/lockbook)
```

2021-08-01 17:33 UTC, steverusso requested changes

2021-08-01 17:33 UTC, steverusso commented on clients/linux/src/account.rs
> +                |w, evt| {
?

2021-08-01 17:33 UTC, steverusso commented on clients/linux/src/account.rs
> +        );
?

2021-08-02 16:37 UTC, steverusso requested changes

2021-08-02 16:37 UTC, steverusso commented on clients/linux/src/account.rs
> +
I don't like seeing file i/o code mixed in with gui code unless it's absolutely necessary. Is this something that can be done when the app is initialized on startup?

2021-08-02 16:37 UTC, steverusso commented on clients/linux/src/account.rs
>  use crate::util::{gui as gui_util, gui::RIGHT_CLICK};
Please give the imports a once over in the future. Right here, LEFT_CLICK can just be appended to the util import right below it.

2021-08-06 20:07 UTC, Parth requested changes
This is great, long awaited, works pretty well.

The links do need to start with roots tho, and we should probably change the behavior of that top bar. I think it's a direction @steverusso is not going to be a fan of, but the motivation is:

One of the constraints of sharing is that every document must have an absolute / universal path. Sharing will likely work similarly to github organizations / slack workspaces / 1password vaults.

So if you're chatting with a team, in slack, or github, you'll be able to share absolute paths to documents in your shared vaults.

These documents will start with the vaultname. In the future you'll have multiple root folders representing these vaults. An individual may have different vaults with different security profiles.

Details are all up in the air as we iterate on the RFC, but I'm pretty certain I want every document to have an unambiguous and absolute path, so let's head in that direction.

Next steps along the link journey will probably include:

1. Inspired by convo with @steverusso, let's take a look at how we can have the lockbook application respond to system uri requests that start with `lb://`. The individual would be able to create links / shortcuts / keybindings to specific documents within lockbook. That'd be sick.
2. Relative links, I'm probably okay with using a different schema like `lbrel://` for this.
3. Id links, same deal `lbid://`
4. image links -- probably this is a step along the way of markdown rendering within lockbook

2021-08-07 23:57 UTC, Parth requested changes
In the URL bar the root is still missing.

2021-08-07 23:57 UTC, Parth commented on clients/linux/src/app.rs
> +    fn markdown_lb_link_exec(&self, scheme: String, uri: String) -> LbResult<()> {
Everything should take `&str`

2021-08-07 23:57 UTC, Parth commented on clients/linux/src/account.rs
> +                            let whole = capture.get(0).unwrap();
can we just exit this closure or something instead of `unwrap` ing.

2021-08-07 23:57 UTC, Parth commented on clients/linux/src/account.rs
> +                            let whole = capture.get(0).unwrap();
I understand that it's never going to fail because of the for loop

2021-08-08 03:24 UTC, Parth approved these changes

2021-08-08 03:24 UTC, merged